# Site settings
title: Prasanjit Prakash
tag_text: 
description: Prasanjit Prakash's CV
site: davewhipp

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: ["README.md"]
sass:
  style: compressed

theme: jekyll-theme-minimal